name: Create Release Branch and PR
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: '5.14.0'
        required: true
      versionCode:
        description: 'v5.14.0'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number
      run: printf 'ext.version = ${{ github.event.inputs.versionCode }}' > pubspec.yaml
    - name: Commit bump version
      id: make-commit
      run: |
        git add pubspec.yaml
        git commit --message "Bump version"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/v${{ github.event.inputs.versionName }}
          base: develop
          title: v${{ github.event.inputs.versionName }} into develop
          reviewers: ${{ github.event.issue.user.login }}
